// Curated MOS / Rate / AFSC dataset, per branch.
//
// Sourced from publicly published service personnel manuals (Army Pamphlet
// 611-21, NAVPERS 18068F, NAVMC 1200.1, Air Force Officer/Enlisted
// Classification Directories, USSF specialty code listings, USCG Personnel
// Manual). The intent is comprehensive coverage of the codes a real operator
// is likely to type — every published occupational area for every branch is
// represented, with the most common officer and enlisted specialties listed
// per area. Codes are stored in their canonical form (e.g. "11B", "0311",
// "1N0X1", "IT") and lookups normalize via uppercase compare.

import type { Branch } from "./branches";

export interface MosEntry {
  /** Code as a user would type it (e.g. "11B", "6602", "1N3X1", "IT2"). */
  code: string;
  /** Human title of the specialty. */
  title: string;
  /** Optional grouping label (e.g. "Infantry", "Aviation Logistics"). */
  category?: string;
}

const ARMY_MOS: MosEntry[] = [
  // ---- Combat arms ------------------------------------------------------
  { code: "11A", title: "Infantry Officer", category: "Infantry" },
  { code: "11B", title: "Infantryman", category: "Infantry" },
  { code: "11C", title: "Indirect Fire Infantryman", category: "Infantry" },
  { code: "11Z", title: "Infantry Senior Sergeant", category: "Infantry" },
  { code: "12A", title: "Engineer Officer", category: "Engineer" },
  { code: "12B", title: "Combat Engineer", category: "Engineer" },
  { code: "12C", title: "Bridge Crewmember", category: "Engineer" },
  { code: "12D", title: "Diver", category: "Engineer" },
  { code: "12K", title: "Plumber", category: "Engineer" },
  { code: "12M", title: "Firefighter", category: "Engineer" },
  { code: "12N", title: "Horizontal Construction Engineer", category: "Engineer" },
  { code: "12P", title: "Prime Power Production Specialist", category: "Engineer" },
  { code: "12R", title: "Interior Electrician", category: "Engineer" },
  { code: "12T", title: "Technical Engineer", category: "Engineer" },
  { code: "12V", title: "Concrete and Asphalt Equipment Operator", category: "Engineer" },
  { code: "12W", title: "Carpentry and Masonry Specialist", category: "Engineer" },
  { code: "12Y", title: "Geospatial Engineer", category: "Engineer" },
  { code: "13A", title: "Field Artillery Officer", category: "Field Artillery" },
  { code: "13B", title: "Cannon Crewmember", category: "Field Artillery" },
  { code: "13D", title: "Field Artillery Automated Tactical Data Systems Specialist", category: "Field Artillery" },
  { code: "13F", title: "Joint Fire Support Specialist", category: "Field Artillery" },
  { code: "13J", title: "Fire Control Specialist", category: "Field Artillery" },
  { code: "13M", title: "Multiple Launch Rocket System Crewmember", category: "Field Artillery" },
  { code: "13R", title: "Field Artillery Firefinder Radar Operator", category: "Field Artillery" },
  { code: "13Z", title: "Field Artillery Senior Sergeant", category: "Field Artillery" },
  { code: "14A", title: "Air Defense Artillery Officer", category: "Air Defense" },
  { code: "14E", title: "Patriot Fire Control Enhanced Operator/Maintainer", category: "Air Defense" },
  { code: "14G", title: "Air Defense Battle Management System Operator", category: "Air Defense" },
  { code: "14H", title: "Air Defense Enhanced Early Warning System Operator", category: "Air Defense" },
  { code: "14P", title: "Air and Missile Defense Crewmember", category: "Air Defense" },
  { code: "14T", title: "Patriot Launching Station Enhanced Operator/Maintainer", category: "Air Defense" },
  { code: "14Z", title: "Air Defense Artillery Senior Sergeant", category: "Air Defense" },
  { code: "15A", title: "Aviation Officer", category: "Aviation" },
  { code: "15B", title: "Aircraft Powerplant Repairer", category: "Aviation" },
  { code: "15D", title: "Aircraft Powertrain Repairer", category: "Aviation" },
  { code: "15E", title: "Unmanned Aircraft Systems Repairer", category: "Aviation" },
  { code: "15F", title: "Aircraft Electrician", category: "Aviation" },
  { code: "15G", title: "Aircraft Structural Repairer", category: "Aviation" },
  { code: "15H", title: "Aircraft Pneudraulics Repairer", category: "Aviation" },
  { code: "15N", title: "Avionic Mechanic", category: "Aviation" },
  { code: "15P", title: "Aviation Operations Specialist", category: "Aviation" },
  { code: "15Q", title: "Air Traffic Control Operator", category: "Aviation" },
  { code: "15R", title: "AH-64 Attack Helicopter Repairer", category: "Aviation" },
  { code: "15T", title: "UH-60 Helicopter Repairer", category: "Aviation" },
  { code: "15U", title: "CH-47 Helicopter Repairer", category: "Aviation" },
  { code: "15W", title: "Unmanned Aircraft Systems Operator", category: "Aviation" },
  { code: "15Y", title: "AH-64D Armament/Electrical/Avionic Systems Repairer", category: "Aviation" },
  { code: "18A", title: "Special Forces Officer", category: "Special Forces" },
  { code: "18B", title: "Special Forces Weapons Sergeant", category: "Special Forces" },
  { code: "18C", title: "Special Forces Engineer Sergeant", category: "Special Forces" },
  { code: "18D", title: "Special Forces Medical Sergeant", category: "Special Forces" },
  { code: "18E", title: "Special Forces Communications Sergeant", category: "Special Forces" },
  { code: "18F", title: "Special Forces Assistant Operations and Intelligence Sergeant", category: "Special Forces" },
  { code: "18Z", title: "Special Forces Senior Sergeant", category: "Special Forces" },
  { code: "19A", title: "Armor Officer", category: "Armor" },
  { code: "19D", title: "Cavalry Scout", category: "Armor" },
  { code: "19K", title: "M1 Armor Crewman", category: "Armor" },
  { code: "19Z", title: "Armor Senior Sergeant", category: "Armor" },
  // ---- Cyber & EW -------------------------------------------------------
  { code: "17A", title: "Cyber Operations Officer", category: "Cyber" },
  { code: "17B", title: "Cyber Capabilities Development Officer", category: "Cyber" },
  { code: "17C", title: "Cyber Operations Specialist", category: "Cyber" },
  { code: "17E", title: "Electronic Warfare Specialist", category: "Cyber" },
  // ---- Combat support: signal ------------------------------------------
  { code: "25A", title: "Signal Officer", category: "Signal" },
  { code: "25B", title: "Information Technology Specialist", category: "Signal" },
  { code: "25C", title: "Radio Operator-Maintainer", category: "Signal" },
  { code: "25D", title: "Cyber Network Defender", category: "Signal" },
  { code: "25E", title: "Electromagnetic Spectrum Manager", category: "Signal" },
  { code: "25H", title: "Information Services Technician (Warrant)", category: "Signal" },
  { code: "25L", title: "Cable Systems Installer-Maintainer", category: "Signal" },
  { code: "25M", title: "Multimedia Illustrator", category: "Signal" },
  { code: "25N", title: "Nodal Network Systems Operator-Maintainer", category: "Signal" },
  { code: "25P", title: "Microwave Systems Operator-Maintainer", category: "Signal" },
  { code: "25Q", title: "Multichannel Transmission Systems Operator-Maintainer", category: "Signal" },
  { code: "25R", title: "Visual Information Equipment Operator-Maintainer", category: "Signal" },
  { code: "25S", title: "Satellite Communication Systems Operator", category: "Signal" },
  { code: "25U", title: "Signal Support Systems Specialist", category: "Signal" },
  { code: "25V", title: "Combat Documentation/Production Specialist", category: "Signal" },
  { code: "25W", title: "Telecommunications Operations Chief", category: "Signal" },
  { code: "25Z", title: "Visual Information Operations Chief", category: "Signal" },
  // ---- Legal & adjutant general ---------------------------------------
  { code: "27A", title: "Judge Advocate General's Corps Officer", category: "Legal" },
  { code: "27D", title: "Paralegal Specialist", category: "Legal" },
  { code: "42A", title: "Human Resources Specialist", category: "Adjutant General" },
  { code: "42B", title: "Human Resources Officer", category: "Adjutant General" },
  { code: "42R", title: "Musician", category: "Adjutant General" },
  { code: "42S", title: "Special Bandsman", category: "Adjutant General" },
  // ---- Military police ------------------------------------------------
  { code: "31A", title: "Military Police Officer", category: "Military Police" },
  { code: "31B", title: "Military Police", category: "Military Police" },
  { code: "31D", title: "CID Special Agent", category: "Military Police" },
  { code: "31E", title: "Internment/Resettlement Specialist", category: "Military Police" },
  { code: "31K", title: "Military Working Dog Handler", category: "Military Police" },
  // ---- Military intelligence ------------------------------------------
  { code: "35A", title: "Military Intelligence Officer", category: "Military Intelligence" },
  { code: "35D", title: "All Source Intelligence Officer", category: "Military Intelligence" },
  { code: "35E", title: "Counterintelligence Officer", category: "Military Intelligence" },
  { code: "35F", title: "Intelligence Analyst", category: "Military Intelligence" },
  { code: "35G", title: "Geospatial Intelligence Imagery Analyst", category: "Military Intelligence" },
  { code: "35L", title: "Counterintelligence Special Agent", category: "Military Intelligence" },
  { code: "35M", title: "Human Intelligence Collector", category: "Military Intelligence" },
  { code: "35N", title: "Signals Intelligence Analyst", category: "Military Intelligence" },
  { code: "35P", title: "Cryptologic Linguist", category: "Military Intelligence" },
  { code: "35Q", title: "Cryptologic Cyberspace Intelligence Collector/Analyst", category: "Military Intelligence" },
  { code: "35S", title: "Signals Collector/Analyst", category: "Military Intelligence" },
  { code: "35T", title: "Military Intelligence Systems Maintainer/Integrator", category: "Military Intelligence" },
  { code: "35V", title: "Senior Signals Intelligence Sergeant", category: "Military Intelligence" },
  { code: "35X", title: "Intelligence Senior Sergeant", category: "Military Intelligence" },
  { code: "35Y", title: "Counterintelligence/Human Intelligence Senior Sergeant", category: "Military Intelligence" },
  { code: "35Z", title: "Signals Intelligence Senior Sergeant", category: "Military Intelligence" },
  // ---- Special operations / civil affairs / PSYOP ----------------------
  { code: "37A", title: "Psychological Operations Officer", category: "Special Operations" },
  { code: "37F", title: "Psychological Operations Specialist", category: "Special Operations" },
  { code: "37X", title: "Psychological Operations Senior Sergeant", category: "Special Operations" },
  { code: "38A", title: "Civil Affairs Officer", category: "Special Operations" },
  { code: "38B", title: "Civil Affairs Specialist", category: "Special Operations" },
  // ---- Finance & comptroller ------------------------------------------
  { code: "44A", title: "Finance Officer", category: "Finance" },
  { code: "36B", title: "Financial Management Technician", category: "Finance" },
  { code: "44C", title: "Comptroller", category: "Finance" },
  // ---- Chaplain --------------------------------------------------------
  { code: "56A", title: "Command and Unit Chaplain", category: "Chaplain" },
  { code: "56M", title: "Religious Affairs Specialist", category: "Chaplain" },
  // ---- Cyber/Telecom officer warrant family ----------------------------
  { code: "63A", title: "Telecommunications Systems Engineer", category: "Cyber/Electronic Warfare" },
  { code: "63B", title: "Telecommunications Operator", category: "Cyber/Electronic Warfare" },
  // ---- Medical Service Corps / AMEDD ----------------------------------
  { code: "60A", title: "Operational Medicine Officer", category: "Medical" },
  { code: "61A", title: "Nuclear Medical Officer", category: "Medical" },
  { code: "62B", title: "Field Surgeon", category: "Medical" },
  { code: "65B", title: "Physical Therapist", category: "Medical" },
  { code: "65D", title: "Physician Assistant", category: "Medical" },
  { code: "66B", title: "Army Public Health Nurse", category: "Medical" },
  { code: "66H", title: "Medical-Surgical Nurse", category: "Medical" },
  { code: "67B", title: "Laboratory Sciences Officer", category: "Medical" },
  { code: "67E", title: "Pharmacy Officer", category: "Medical" },
  { code: "68A", title: "Biomedical Equipment Specialist", category: "Medical" },
  { code: "68B", title: "Orthopaedic Specialist", category: "Medical" },
  { code: "68C", title: "Practical Nursing Specialist", category: "Medical" },
  { code: "68D", title: "Operating Room Specialist", category: "Medical" },
  { code: "68E", title: "Dental Specialist", category: "Medical" },
  { code: "68F", title: "Physical Therapy Specialist", category: "Medical" },
  { code: "68G", title: "Patient Administration Specialist", category: "Medical" },
  { code: "68H", title: "Optical Laboratory Specialist", category: "Medical" },
  { code: "68J", title: "Medical Logistics Specialist", category: "Medical" },
  { code: "68K", title: "Medical Laboratory Specialist", category: "Medical" },
  { code: "68P", title: "Radiology Specialist", category: "Medical" },
  { code: "68Q", title: "Pharmacy Specialist", category: "Medical" },
  { code: "68R", title: "Veterinary Food Inspection Specialist", category: "Medical" },
  { code: "68S", title: "Preventive Medicine Specialist", category: "Medical" },
  { code: "68T", title: "Animal Care Specialist", category: "Medical" },
  { code: "68V", title: "Respiratory Specialist", category: "Medical" },
  { code: "68W", title: "Combat Medic Specialist", category: "Medical" },
  { code: "68X", title: "Behavioral Health Specialist", category: "Medical" },
  { code: "68Y", title: "Eye Specialist", category: "Medical" },
  { code: "70B", title: "Health Services Administration", category: "Medical" },
  { code: "74D", title: "Chemical, Biological, Radiological, Nuclear Specialist", category: "CBRN" },
  // ---- Transportation -------------------------------------------------
  { code: "88H", title: "Cargo Specialist", category: "Transportation" },
  { code: "88K", title: "Watercraft Operator", category: "Transportation" },
  { code: "88L", title: "Watercraft Engineer", category: "Transportation" },
  { code: "88M", title: "Motor Transport Operator", category: "Transportation" },
  { code: "88N", title: "Transportation Management Coordinator", category: "Transportation" },
  { code: "88P", title: "Railway Equipment Repairer", category: "Transportation" },
  { code: "88U", title: "Railway Operations Crewmember", category: "Transportation" },
  // ---- Ordnance & maintenance -----------------------------------------
  { code: "89A", title: "Ammunition Stock Control and Accounting Specialist", category: "Ordnance" },
  { code: "89B", title: "Ammunition Specialist", category: "Ordnance" },
  { code: "89D", title: "Explosive Ordnance Disposal Specialist", category: "Ordnance" },
  { code: "91A", title: "M1 Abrams Tank System Maintainer", category: "Mechanical Maintenance" },
  { code: "91B", title: "Wheeled Vehicle Mechanic", category: "Mechanical Maintenance" },
  { code: "91C", title: "Utilities Equipment Repairer", category: "Mechanical Maintenance" },
  { code: "91D", title: "Tactical Power Generation Specialist", category: "Mechanical Maintenance" },
  { code: "91E", title: "Allied Trades Specialist", category: "Mechanical Maintenance" },
  { code: "91F", title: "Small Arms/Artillery Repairer", category: "Mechanical Maintenance" },
  { code: "91H", title: "Track Vehicle Repairer", category: "Mechanical Maintenance" },
  { code: "91J", title: "Quartermaster and Chemical Equipment Repairer", category: "Mechanical Maintenance" },
  { code: "91L", title: "Construction Equipment Repairer", category: "Mechanical Maintenance" },
  { code: "91M", title: "Bradley Fighting Vehicle System Maintainer", category: "Mechanical Maintenance" },
  { code: "91P", title: "Self-Propelled Artillery Systems Maintainer", category: "Mechanical Maintenance" },
  { code: "91S", title: "Stryker Systems Maintainer", category: "Mechanical Maintenance" },
  // ---- Quartermaster --------------------------------------------------
  { code: "92A", title: "Automated Logistical Specialist", category: "Quartermaster" },
  { code: "92F", title: "Petroleum Supply Specialist", category: "Quartermaster" },
  { code: "92G", title: "Culinary Specialist", category: "Quartermaster" },
  { code: "92L", title: "Petroleum Laboratory Specialist", category: "Quartermaster" },
  { code: "92M", title: "Mortuary Affairs Specialist", category: "Quartermaster" },
  { code: "92R", title: "Parachute Rigger", category: "Quartermaster" },
  { code: "92S", title: "Shower/Laundry and Clothing Repair Specialist", category: "Quartermaster" },
  { code: "92W", title: "Water Treatment Specialist", category: "Quartermaster" },
  { code: "92Y", title: "Unit Supply Specialist", category: "Quartermaster" },
  // ---- Electronic maintenance -----------------------------------------
  { code: "94A", title: "Land Combat Electronic Missile System Repairer", category: "Electronic Maintenance" },
  { code: "94D", title: "Air Traffic Control Equipment Repairer", category: "Electronic Maintenance" },
  { code: "94E", title: "Radio and Communications Security Repairer", category: "Electronic Maintenance" },
  { code: "94F", title: "Computer/Detection Systems Repairer", category: "Electronic Maintenance" },
  { code: "94H", title: "Test, Measurement, and Diagnostic Equipment Maintenance Support Specialist", category: "Electronic Maintenance" },
  { code: "94M", title: "Radar Repairer", category: "Electronic Maintenance" },
  { code: "94P", title: "Multiple Launch Rocket System Repairer", category: "Electronic Maintenance" },
  { code: "94R", title: "Avionic and Survivability Equipment Repairer", category: "Electronic Maintenance" },
  { code: "94S", title: "Patriot System Repairer", category: "Electronic Maintenance" },
  { code: "94T", title: "Avenger System Repairer", category: "Electronic Maintenance" },
  { code: "94W", title: "Electronic Maintenance Chief", category: "Electronic Maintenance" },
  { code: "94Y", title: "Integrated Family of Test Equipment Operator/Maintainer", category: "Electronic Maintenance" },
  { code: "94Z", title: "Senior Electronic Maintenance Chief", category: "Electronic Maintenance" },
];

const NAVY_RATINGS: MosEntry[] = [
  // ---- Surface / Deck / Weapons ---------------------------------------
  { code: "BM", title: "Boatswain's Mate", category: "Deck" },
  { code: "QM", title: "Quartermaster", category: "Deck" },
  { code: "GM", title: "Gunner's Mate", category: "Weapons" },
  { code: "MN", title: "Mineman", category: "Weapons" },
  { code: "FT", title: "Fire Control Technician (Submarine)", category: "Combat Systems" },
  { code: "FC", title: "Fire Controlman", category: "Combat Systems" },
  { code: "FCA", title: "Fire Controlman (AEGIS)", category: "Combat Systems" },
  { code: "OS", title: "Operations Specialist", category: "Combat Systems" },
  { code: "ST", title: "Sonar Technician (Surface)", category: "Combat Systems" },
  // ---- Engineering ----------------------------------------------------
  { code: "EM", title: "Electrician's Mate", category: "Engineering" },
  { code: "EN", title: "Engineman", category: "Engineering" },
  { code: "MM", title: "Machinist's Mate", category: "Engineering" },
  { code: "GSM", title: "Gas Turbine Systems Technician (Mechanical)", category: "Engineering" },
  { code: "GSE", title: "Gas Turbine Systems Technician (Electrical)", category: "Engineering" },
  { code: "DC", title: "Damage Controlman", category: "Engineering" },
  { code: "HT", title: "Hull Maintenance Technician", category: "Engineering" },
  { code: "EM (NUC)", title: "Electrician's Mate (Nuclear)", category: "Engineering" },
  { code: "MM (NUC)", title: "Machinist's Mate (Nuclear)", category: "Engineering" },
  { code: "ET (NUC)", title: "Electronics Technician (Nuclear)", category: "Engineering" },
  // ---- Aviation -------------------------------------------------------
  { code: "AB", title: "Aviation Boatswain's Mate", category: "Aviation" },
  { code: "ABE", title: "Aviation Boatswain's Mate (Equipment)", category: "Aviation" },
  { code: "ABF", title: "Aviation Boatswain's Mate (Fuel)", category: "Aviation" },
  { code: "ABH", title: "Aviation Boatswain's Mate (Handling)", category: "Aviation" },
  { code: "AC", title: "Air Traffic Controller", category: "Aviation" },
  { code: "AD", title: "Aviation Machinist's Mate", category: "Aviation" },
  { code: "AE", title: "Aviation Electrician's Mate", category: "Aviation" },
  { code: "AG", title: "Aerographer's Mate", category: "Aviation" },
  { code: "AT", title: "Aviation Electronics Technician", category: "Aviation" },
  { code: "AO", title: "Aviation Ordnanceman", category: "Aviation" },
  { code: "AM", title: "Aviation Structural Mechanic", category: "Aviation" },
  { code: "AME", title: "Aviation Structural Mechanic (Safety Equipment)", category: "Aviation" },
  { code: "AS", title: "Aviation Support Equipment Technician", category: "Aviation" },
  { code: "AZ", title: "Aviation Maintenance Administrationman", category: "Aviation" },
  { code: "PR", title: "Aircrew Survival Equipmentman", category: "Aviation" },
  { code: "AWO", title: "Naval Aircrewman Operator", category: "Aviation" },
  { code: "AWF", title: "Naval Aircrewman Mechanical", category: "Aviation" },
  { code: "AWS", title: "Naval Aircrewman Helicopter", category: "Aviation" },
  { code: "AWV", title: "Naval Aircrewman Avionics", category: "Aviation" },
  { code: "AWR", title: "Naval Aircrewman Tactical Helicopter", category: "Aviation" },
  // ---- Information / Cryptology ---------------------------------------
  { code: "IT", title: "Information Systems Technician", category: "Information Warfare" },
  { code: "ITS", title: "Information Systems Technician (Submarines)", category: "Information Warfare" },
  { code: "CTI", title: "Cryptologic Technician Interpretive", category: "Information Warfare" },
  { code: "CTM", title: "Cryptologic Technician Maintenance", category: "Information Warfare" },
  { code: "CTN", title: "Cryptologic Technician Networks", category: "Information Warfare" },
  { code: "CTR", title: "Cryptologic Technician Collection", category: "Information Warfare" },
  { code: "CTT", title: "Cryptologic Technician Technical", category: "Information Warfare" },
  { code: "IS", title: "Intelligence Specialist", category: "Information Warfare" },
  // ---- Submarine ------------------------------------------------------
  { code: "ETV", title: "Electronics Technician (Submarine, Navigation)", category: "Submarines" },
  { code: "ETR", title: "Electronics Technician (Submarine, Communications)", category: "Submarines" },
  { code: "STS", title: "Sonar Technician (Submarine)", category: "Submarines" },
  { code: "MMA", title: "Machinist's Mate (Auxiliary)", category: "Submarines" },
  { code: "MMW", title: "Machinist's Mate (Weapons)", category: "Submarines" },
  { code: "MMN", title: "Machinist's Mate (Submarine Nuclear)", category: "Submarines" },
  { code: "TM", title: "Torpedoman's Mate (Submarine)", category: "Submarines" },
  { code: "MT", title: "Missile Technician (Submarine)", category: "Submarines" },
  { code: "CS (SS)", title: "Culinary Specialist (Submarine)", category: "Submarines" },
  { code: "YN (SS)", title: "Yeoman (Submarine)", category: "Submarines" },
  { code: "LS (SS)", title: "Logistics Specialist (Submarine)", category: "Submarines" },
  // ---- Medical / Dental / Admin ---------------------------------------
  { code: "HM", title: "Hospital Corpsman", category: "Medical" },
  { code: "DT", title: "Dental Technician", category: "Medical" },
  { code: "PS", title: "Personnel Specialist", category: "Administration" },
  { code: "YN", title: "Yeoman", category: "Administration" },
  { code: "LS", title: "Logistics Specialist", category: "Supply" },
  { code: "CS", title: "Culinary Specialist", category: "Supply" },
  { code: "RP", title: "Religious Program Specialist", category: "Administration" },
  { code: "MA", title: "Master-at-Arms", category: "Security" },
  { code: "MC", title: "Mass Communication Specialist", category: "Public Affairs" },
  { code: "MU", title: "Musician", category: "Administration" },
  // ---- Construction (Seabees) -----------------------------------------
  { code: "BU", title: "Builder", category: "Construction" },
  { code: "CE", title: "Construction Electrician", category: "Construction" },
  { code: "CM", title: "Construction Mechanic", category: "Construction" },
  { code: "EA", title: "Engineering Aid", category: "Construction" },
  { code: "EO", title: "Equipment Operator", category: "Construction" },
  { code: "SW", title: "Steelworker", category: "Construction" },
  { code: "UT", title: "Utilitiesman", category: "Construction" },
  // ---- Special warfare ------------------------------------------------
  { code: "SO", title: "Special Warfare Operator (SEAL)", category: "Special Warfare" },
  { code: "SB", title: "Special Warfare Boat Operator (SWCC)", category: "Special Warfare" },
  { code: "EOD", title: "Explosive Ordnance Disposal Technician", category: "Special Warfare" },
  { code: "ND", title: "Navy Diver", category: "Special Warfare" },
  // ---- Officer designators -------------------------------------------
  { code: "1110", title: "Surface Warfare Officer", category: "Officer Designator" },
  { code: "1120", title: "Submarine Officer", category: "Officer Designator" },
  { code: "1130", title: "Special Warfare Officer (SEAL)", category: "Officer Designator" },
  { code: "1140", title: "Explosive Ordnance Disposal Officer", category: "Officer Designator" },
  { code: "1310", title: "Naval Aviator", category: "Officer Designator" },
  { code: "1320", title: "Naval Flight Officer", category: "Officer Designator" },
  { code: "1810", title: "Cryptologic Warfare Officer", category: "Officer Designator" },
  { code: "1820", title: "Information Professional Officer", category: "Officer Designator" },
  { code: "1830", title: "Intelligence Officer", category: "Officer Designator" },
  { code: "1840", title: "Cyber Warfare Engineer", category: "Officer Designator" },
  { code: "2100", title: "Medical Corps Officer", category: "Officer Designator" },
  { code: "2200", title: "Dental Corps Officer", category: "Officer Designator" },
  { code: "2300", title: "Medical Service Corps Officer", category: "Officer Designator" },
  { code: "2900", title: "Nurse Corps Officer", category: "Officer Designator" },
  { code: "3100", title: "Supply Corps Officer", category: "Officer Designator" },
  { code: "4100", title: "Chaplain Corps Officer", category: "Officer Designator" },
  { code: "5100", title: "Civil Engineer Corps Officer", category: "Officer Designator" },
];

const USMC_MOS: MosEntry[] = [
  // ---- 01 Personnel & Administration ----------------------------------
  { code: "0102", title: "Personnel Officer", category: "Personnel & Administration" },
  { code: "0111", title: "Administrative Specialist", category: "Personnel & Administration" },
  { code: "0151", title: "Manpower Information Systems Analyst", category: "Personnel & Administration" },
  { code: "0170", title: "Manpower Officer", category: "Personnel & Administration" },
  // ---- 02 Intelligence ------------------------------------------------
  { code: "0202", title: "MAGTF Intelligence Officer", category: "Intelligence" },
  { code: "0203", title: "Ground Intelligence Officer", category: "Intelligence" },
  { code: "0204", title: "Counterintelligence/HUMINT Officer", category: "Intelligence" },
  { code: "0205", title: "Senior Intelligence Analyst", category: "Intelligence" },
  { code: "0206", title: "Signals Intelligence/Electronic Warfare Officer", category: "Intelligence" },
  { code: "0207", title: "Imagery Intelligence Officer", category: "Intelligence" },
  { code: "0211", title: "Counterintelligence/HUMINT Specialist", category: "Intelligence" },
  { code: "0231", title: "Intelligence Specialist", category: "Intelligence" },
  { code: "0241", title: "Geographic Intelligence Specialist", category: "Intelligence" },
  { code: "0261", title: "Geospatial Intelligence Specialist", category: "Intelligence" },
  { code: "0291", title: "Intelligence Chief", category: "Intelligence" },
  // ---- 03 Infantry ----------------------------------------------------
  { code: "0302", title: "Infantry Officer", category: "Infantry" },
  { code: "0311", title: "Rifleman", category: "Infantry" },
  { code: "0313", title: "Light Armored Reconnaissance Marine", category: "Infantry" },
  { code: "0317", title: "Reconnaissance Marine (Scout Sniper)", category: "Infantry" },
  { code: "0321", title: "Reconnaissance Marine", category: "Infantry" },
  { code: "0331", title: "Machine Gunner", category: "Infantry" },
  { code: "0341", title: "Mortarman", category: "Infantry" },
  { code: "0351", title: "Infantry Assault Marine", category: "Infantry" },
  { code: "0352", title: "Antitank Missileman", category: "Infantry" },
  { code: "0365", title: "Infantry Squad Leader", category: "Infantry" },
  { code: "0369", title: "Infantry Unit Leader", category: "Infantry" },
  { code: "0372", title: "Critical Skills Operator (MARSOC)", category: "Special Operations" },
  { code: "0399", title: "Infantry Sergeant Major", category: "Infantry" },
  // ---- 04 Logistics ---------------------------------------------------
  { code: "0402", title: "Logistics Officer", category: "Logistics" },
  { code: "0411", title: "Maintenance Management Specialist", category: "Logistics" },
  { code: "0431", title: "Logistics/Embarkation Specialist", category: "Logistics" },
  { code: "0451", title: "Airborne and Air Delivery Specialist", category: "Logistics" },
  { code: "0481", title: "Landing Support Specialist", category: "Logistics" },
  { code: "0491", title: "Logistics Operations Chief", category: "Logistics" },
  // ---- 05 MAGTF Plans -------------------------------------------------
  { code: "0505", title: "MAGTF Planner", category: "MAGTF Plans" },
  { code: "0540", title: "MAGTF Planning Specialist", category: "MAGTF Plans" },
  // ---- 06 Communications ----------------------------------------------
  { code: "0602", title: "Communications Officer", category: "Communications" },
  { code: "0612", title: "Tactical Switching Operator", category: "Communications" },
  { code: "0621", title: "Radio Operator", category: "Communications" },
  { code: "0629", title: "Communications Chief", category: "Communications" },
  { code: "0631", title: "Network Administrator", category: "Communications" },
  { code: "0651", title: "Cyber Network Operator", category: "Communications" },
  { code: "0671", title: "Data Systems Administrator", category: "Communications" },
  { code: "0681", title: "Information Security Technician", category: "Communications" },
  // ---- 08 Field Artillery ---------------------------------------------
  { code: "0802", title: "Field Artillery Officer", category: "Field Artillery" },
  { code: "0811", title: "Field Artillery Cannoneer", category: "Field Artillery" },
  { code: "0814", title: "High Mobility Artillery Rocket System Operator", category: "Field Artillery" },
  { code: "0842", title: "Field Artillery Radar Operator", category: "Field Artillery" },
  { code: "0844", title: "Field Artillery Fire Control Marine", category: "Field Artillery" },
  { code: "0848", title: "Field Artillery Operations Chief", category: "Field Artillery" },
  { code: "0861", title: "Fire Support Marine", category: "Field Artillery" },
  // ---- 11 Utilities ---------------------------------------------------
  { code: "1141", title: "Electrician", category: "Utilities" },
  { code: "1142", title: "Engineer Equipment Electrical Systems Technician", category: "Utilities" },
  { code: "1161", title: "Refrigeration and Air Conditioning Technician", category: "Utilities" },
  { code: "1171", title: "Hygiene Equipment Operator", category: "Utilities" },
  { code: "1181", title: "Fabric Repair Specialist", category: "Utilities" },
  // ---- 13 Engineer / Construction -------------------------------------
  { code: "1302", title: "Combat Engineer Officer", category: "Engineer" },
  { code: "1310", title: "Engineer Equipment Officer", category: "Engineer" },
  { code: "1316", title: "Metal Worker", category: "Engineer" },
  { code: "1341", title: "Engineer Equipment Mechanic", category: "Engineer" },
  { code: "1345", title: "Engineer Equipment Operator", category: "Engineer" },
  { code: "1361", title: "Engineer Assistant", category: "Engineer" },
  { code: "1371", title: "Combat Engineer", category: "Engineer" },
  { code: "1391", title: "Bulk Fuel Specialist", category: "Engineer" },
  // ---- 18 Tank/AAV/LAV ------------------------------------------------
  { code: "1802", title: "Tank Officer", category: "Armor" },
  { code: "1803", title: "Assault Amphibious Vehicle Officer", category: "Armor" },
  { code: "1812", title: "Tank Crewman", category: "Armor" },
  { code: "1833", title: "Assault Amphibious Vehicle Crewman", category: "Armor" },
  // ---- 21 Ground Ordnance ---------------------------------------------
  { code: "2102", title: "Ordnance Officer", category: "Ordnance" },
  { code: "2111", title: "Small Arms Repairer/Technician", category: "Ordnance" },
  { code: "2131", title: "Towed Artillery Systems Technician", category: "Ordnance" },
  { code: "2141", title: "Assault Amphibious Vehicle Repairer/Technician", category: "Ordnance" },
  { code: "2147", title: "Light Armored Vehicle Repairer/Technician", category: "Ordnance" },
  { code: "2161", title: "Machinist", category: "Ordnance" },
  { code: "2171", title: "Electro-Optical Ordnance Repairer", category: "Ordnance" },
  { code: "2181", title: "Senior Ordnance Vehicle Maintenance Chief", category: "Ordnance" },
  // ---- 23 Ammunition / EOD -------------------------------------------
  { code: "2302", title: "Explosive Ordnance Disposal Officer", category: "Ordnance" },
  { code: "2305", title: "Ammunition Officer", category: "Ordnance" },
  { code: "2311", title: "Ammunition Technician", category: "Ordnance" },
  { code: "2336", title: "Explosive Ordnance Disposal Technician", category: "Ordnance" },
  // ---- 26 Signals Intelligence / EW -----------------------------------
  { code: "2611", title: "Cryptologic Digital Network Technician/Analyst", category: "SIGINT" },
  { code: "2621", title: "Special Communications Signals Collection Operator/Analyst", category: "SIGINT" },
  { code: "2629", title: "Signals Intelligence Analyst", category: "SIGINT" },
  { code: "2631", title: "Electronic Intelligence Intercept Operator/Analyst", category: "SIGINT" },
  // ---- 28 Ground Electronics Maintenance ------------------------------
  { code: "2802", title: "Ground Electronics Maintenance Officer", category: "Electronics Maintenance" },
  { code: "2823", title: "Technical Control Marine", category: "Electronics Maintenance" },
  { code: "2841", title: "Ground Electronics Transmission Systems Maintainer", category: "Electronics Maintenance" },
  { code: "2862", title: "Electronics Maintenance Technician", category: "Electronics Maintenance" },
  // ---- 30 Supply Administration ---------------------------------------
  { code: "3002", title: "Ground Supply Officer", category: "Supply" },
  { code: "3043", title: "Supply Administration Operations Specialist", category: "Supply" },
  { code: "3051", title: "Warehouse Clerk", category: "Supply" },
  { code: "3052", title: "Packaging Specialist", category: "Supply" },
  // ---- 31 Distribution Management -------------------------------------
  { code: "3112", title: "Traffic Management Specialist", category: "Distribution" },
  // ---- 33 Food Service ------------------------------------------------
  { code: "3302", title: "Food Service Officer", category: "Food Service" },
  { code: "3372", title: "Food Service Specialist", category: "Food Service" },
  // ---- 34 Financial Management ----------------------------------------
  { code: "3402", title: "Financial Management Officer", category: "Finance" },
  { code: "3432", title: "Finance Technician", category: "Finance" },
  { code: "3451", title: "Fiscal/Budget Technician", category: "Finance" },
  // ---- 35 Motor Transport ---------------------------------------------
  { code: "3510", title: "Motor Transport Maintenance Officer", category: "Motor Transport" },
  { code: "3521", title: "Organizational Automotive Mechanic", category: "Motor Transport" },
  { code: "3531", title: "Motor Vehicle Operator", category: "Motor Transport" },
  { code: "3537", title: "Motor Transport Operations Chief", category: "Motor Transport" },
  // ---- 41 Marine Corps Exchange / Family Readiness --------------------
  { code: "4133", title: "Marine Corps Community Services Marine", category: "Community Services" },
  // ---- 43 Public Affairs ----------------------------------------------
  { code: "4302", title: "Public Affairs Officer", category: "Public Affairs" },
  { code: "4341", title: "Combat Correspondent", category: "Public Affairs" },
  // ---- 44 Legal --------------------------------------------------------
  { code: "4402", title: "Judge Advocate", category: "Legal" },
  { code: "4421", title: "Legal Services Specialist", category: "Legal" },
  // ---- 46 Combat Camera -----------------------------------------------
  { code: "4602", title: "Combat Camera Officer", category: "Combat Camera" },
  { code: "4611", title: "Combat Photographer", category: "Combat Camera" },
  { code: "4612", title: "Combat Videographer", category: "Combat Camera" },
  // ---- 55 Music --------------------------------------------------------
  { code: "5511", title: "U.S. Marine Band Member", category: "Music" },
  // ---- 57 NBC Defense -------------------------------------------------
  { code: "5702", title: "CBRN Defense Officer", category: "CBRN" },
  { code: "5711", title: "CBRN Defense Specialist", category: "CBRN" },
  // ---- 58 Military Police / Corrections -------------------------------
  { code: "5803", title: "Military Police Officer", category: "Military Police" },
  { code: "5811", title: "Military Police", category: "Military Police" },
  { code: "5812", title: "Military Working Dog Handler", category: "Military Police" },
  { code: "5821", title: "Criminal Investigator", category: "Military Police" },
  // ---- 60-69 Aircraft Maintenance / Aviation Logistics ----------------
  { code: "6002", title: "Aircraft Maintenance Officer", category: "Aviation Maintenance" },
  { code: "6004", title: "Aircraft Maintenance Engineer Officer", category: "Aviation Maintenance" },
  { code: "6212", title: "Fixed-Wing Aircraft Mechanic, F/A-18", category: "Aircraft Maintenance" },
  { code: "6217", title: "Fixed-Wing Aircraft Mechanic, F-35", category: "Aircraft Maintenance" },
  { code: "6321", title: "Aircraft Communications/Navigation/Radar Systems Technician, F/A-18", category: "Aircraft Maintenance" },
  { code: "6602", title: "Aviation Logistics Information Management Systems Officer", category: "Aviation Logistics" },
  { code: "6604", title: "Aviation Maintenance Materiel Control Officer", category: "Aviation Logistics" },
  { code: "6672", title: "Aviation Supply Chief", category: "Aviation Logistics" },
  // ---- 72-73 Air Control / Air Support / Anti-Air Warfare -------------
  { code: "7202", title: "Air Command and Control / Anti-Air Warfare Officer", category: "Air Control" },
  { code: "7212", title: "Low Altitude Air Defense Officer", category: "Air Defense" },
  { code: "7236", title: "Tactical Air Defense Controller", category: "Air Control" },
  { code: "7242", title: "Air Support Operations Operator", category: "Air Control" },
  { code: "7257", title: "Air Traffic Controller", category: "Air Control" },
  // ---- 75 Pilots / NFOs -----------------------------------------------
  { code: "7509", title: "Pilot, Trainee", category: "Aviation" },
  { code: "7521", title: "Pilot, AV-8B", category: "Aviation" },
  { code: "7523", title: "Pilot, F/A-18", category: "Aviation" },
  { code: "7525", title: "Pilot, EA-18G/EA-6B", category: "Aviation" },
  { code: "7532", title: "Pilot, KC-130", category: "Aviation" },
  { code: "7556", title: "Pilot, MV-22", category: "Aviation" },
  { code: "7557", title: "Pilot, F-35B/C", category: "Aviation" },
  { code: "7563", title: "UH-1Y Pilot", category: "Aviation" },
  { code: "7565", title: "Pilot, CH-53E/K", category: "Aviation" },
  { code: "7566", title: "AH-1Z Pilot", category: "Aviation" },
];

const AIR_FORCE_AFSC: MosEntry[] = [
  // ---- 11 Pilot --------------------------------------------------------
  { code: "11FX", title: "Fighter Pilot", category: "Pilot" },
  { code: "11BX", title: "Bomber Pilot", category: "Pilot" },
  { code: "11RX", title: "Reconnaissance/Surveillance/Electronic Warfare Pilot", category: "Pilot" },
  { code: "11MX", title: "Mobility Pilot", category: "Pilot" },
  { code: "11HX", title: "Helicopter Pilot", category: "Pilot" },
  { code: "11SX", title: "Special Operations Pilot", category: "Pilot" },
  { code: "11UX", title: "Remotely Piloted Aircraft Pilot", category: "Pilot" },
  // ---- 12 Combat Systems Officer / Air Battle Manager -----------------
  { code: "12BX", title: "Bomber Combat Systems Officer", category: "Combat Systems Officer" },
  { code: "12FX", title: "Fighter Combat Systems Officer", category: "Combat Systems Officer" },
  { code: "12MX", title: "Mobility Combat Systems Officer", category: "Combat Systems Officer" },
  { code: "12RX", title: "Reconnaissance Combat Systems Officer", category: "Combat Systems Officer" },
  { code: "12SX", title: "Special Operations Combat Systems Officer", category: "Combat Systems Officer" },
  // ---- 13 Operations ---------------------------------------------------
  { code: "13BX", title: "Air Battle Manager", category: "Operations" },
  { code: "13CX", title: "Special Tactics Officer", category: "Special Warfare" },
  { code: "13DX", title: "Combat Rescue Officer", category: "Special Warfare" },
  { code: "13LX", title: "Air Liaison Officer", category: "Operations" },
  { code: "13MX", title: "Airfield Operations Officer", category: "Operations" },
  { code: "13NX", title: "Nuclear and Missile Operations", category: "Operations" },
  { code: "13SX", title: "Space Operations", category: "Operations" },
  // ---- 14 Intelligence -------------------------------------------------
  { code: "14NX", title: "Intelligence Officer", category: "Intelligence" },
  { code: "14FX", title: "Information Operations Officer", category: "Intelligence" },
  // ---- 15 Weather ------------------------------------------------------
  { code: "15WX", title: "Weather Officer", category: "Operations" },
  // ---- 17 Cyber --------------------------------------------------------
  { code: "17DX", title: "Cyberspace Operations Officer", category: "Cyber" },
  { code: "17SX", title: "Cyber Warfare Operations Officer", category: "Cyber" },
  // ---- 21 Logistics ----------------------------------------------------
  { code: "21AX", title: "Aircraft Maintenance Officer", category: "Logistics" },
  { code: "21MX", title: "Munitions and Missile Maintenance Officer", category: "Logistics" },
  { code: "21RX", title: "Logistics Readiness Officer", category: "Logistics" },
  // ---- 31 Security Forces ---------------------------------------------
  { code: "31PX", title: "Security Forces Officer", category: "Security Forces" },
  // ---- 32 Civil Engineer ----------------------------------------------
  { code: "32EX", title: "Civil Engineer Officer", category: "Civil Engineer" },
  // ---- 35 Public Affairs ----------------------------------------------
  { code: "35PX", title: "Public Affairs Officer", category: "Public Affairs" },
  // ---- 38 Force Support / Personnel -----------------------------------
  { code: "38FX", title: "Force Support Officer", category: "Personnel" },
  // ---- 41 Health Services ---------------------------------------------
  { code: "41AX", title: "Health Services Administrator", category: "Medical" },
  // ---- 42 Medical Service ---------------------------------------------
  { code: "42BX", title: "Physical Therapist", category: "Medical" },
  { code: "42EX", title: "Optometrist", category: "Medical" },
  { code: "42GX", title: "Physician Assistant", category: "Medical" },
  { code: "42PX", title: "Clinical Psychologist", category: "Medical" },
  { code: "42SX", title: "Clinical Social Worker", category: "Medical" },
  // ---- 1A Aircrew (Enlisted) ------------------------------------------
  { code: "1A0X1", title: "In-Flight Refueling Specialist", category: "Aircrew" },
  { code: "1A1X1", title: "Flight Engineer", category: "Aircrew" },
  { code: "1A2X1", title: "Aircraft Loadmaster", category: "Aircrew" },
  { code: "1A3X1", title: "Airborne Mission Systems Specialist", category: "Aircrew" },
  { code: "1A6X1", title: "Flight Attendant", category: "Aircrew" },
  { code: "1A8X1", title: "Airborne Linguist", category: "Aircrew" },
  { code: "1A8X2", title: "Airborne ISR Operator", category: "Aircrew" },
  { code: "1A9X1", title: "Special Missions Aviation", category: "Aircrew" },
  // ---- 1B Cyber Warfare -----------------------------------------------
  { code: "1B4X1", title: "Cyber Warfare Operations", category: "Cyber" },
  // ---- 1C Command and Control -----------------------------------------
  { code: "1C0X2", title: "Aviation Resource Management", category: "Operations" },
  { code: "1C1X1", title: "Air Traffic Control", category: "Operations" },
  { code: "1C2X1", title: "Combat Control", category: "Special Warfare" },
  { code: "1C3X1", title: "Command Post", category: "Operations" },
  { code: "1C4X1", title: "Tactical Air Control Party", category: "Special Warfare" },
  { code: "1C5X1", title: "Command and Control Battle Management Operations", category: "Operations" },
  { code: "1C6X1", title: "Space Systems Operations", category: "Operations" },
  { code: "1C7X1", title: "Airfield Management", category: "Operations" },
  { code: "1C8X1", title: "Airfield Systems", category: "Operations" },
  // ---- 1D Cyber Defense / Network -------------------------------------
  { code: "1D7X1A", title: "Spectrum Defense Operations (Cyber Defense Operations)", category: "Cyber" },
  { code: "1D7X1B", title: "Network Operations (Cyber Defense Operations)", category: "Cyber" },
  { code: "1D7X1C", title: "Network Systems Operations", category: "Cyber" },
  { code: "1D7X1D", title: "Cable and Antenna Systems", category: "Cyber" },
  { code: "1D7X1E", title: "Radio Frequency Operations", category: "Cyber" },
  { code: "1D7X1F", title: "Spectrum Operations", category: "Cyber" },
  { code: "1D7X1G", title: "Client Systems", category: "Cyber" },
  { code: "1D7X1H", title: "Knowledge Management", category: "Cyber" },
  { code: "1D7X2", title: "Spectrum Operations Technician", category: "Cyber" },
  // ---- 1N Intelligence ------------------------------------------------
  { code: "1N0X1", title: "All Source Intelligence Analyst", category: "Intelligence" },
  { code: "1N0X2", title: "Operations Intelligence", category: "Intelligence" },
  { code: "1N1X1", title: "Geospatial Intelligence", category: "Intelligence" },
  { code: "1N2X1A", title: "Communication Signals Intelligence Analyst", category: "Intelligence" },
  { code: "1N2X1B", title: "Electronic Signals Intelligence Analyst", category: "Intelligence" },
  { code: "1N3X1", title: "Cryptologic Language Analyst", category: "Intelligence" },
  { code: "1N4X1A", title: "Digital Network Analyst", category: "Intelligence" },
  { code: "1N4X1B", title: "Cyber Intelligence Analyst", category: "Intelligence" },
  { code: "1N8X1", title: "Targeting Analyst", category: "Intelligence" },
  // ---- 1P / 1T / 1Z Special Warfare -----------------------------------
  { code: "1P0X1", title: "Aircrew Flight Equipment", category: "Operations" },
  { code: "1T0X1", title: "Survival, Evasion, Resistance, and Escape (SERE)", category: "Special Warfare" },
  { code: "1T2X1", title: "Pararescue", category: "Special Warfare" },
  { code: "1Z2X1", title: "Combat Controller", category: "Special Warfare" },
  { code: "1Z3X1", title: "Pararescue (Apprentice)", category: "Special Warfare" },
  { code: "1Z4X1", title: "Tactical Air Control Party (TACP)", category: "Special Warfare" },
  // ---- 2A Aircraft Maintenance ----------------------------------------
  { code: "2A2X1", title: "Special Operations Forces Aerial Gunner", category: "Maintenance" },
  { code: "2A2X2", title: "Special Operations Forces Aviation Communication Systems", category: "Maintenance" },
  { code: "2A3X3", title: "Tactical Aircraft Maintenance (4th Gen)", category: "Maintenance" },
  { code: "2A3X4", title: "Tactical Aircraft Maintenance (A-10)", category: "Maintenance" },
  { code: "2A3X5", title: "Advanced Fighter Aircraft Integrated Avionics", category: "Maintenance" },
  { code: "2A3X7", title: "Tactical Aircraft Maintenance (F-22)", category: "Maintenance" },
  { code: "2A3X8", title: "Tactical Aircraft Maintenance (5th Gen)", category: "Maintenance" },
  { code: "2A5X1", title: "Airlift/Special Mission Aircraft Maintenance", category: "Maintenance" },
  { code: "2A5X2", title: "Helicopter/Tiltrotor Aircraft Maintenance", category: "Maintenance" },
  { code: "2A5X3", title: "Bomber Aircraft Maintenance", category: "Maintenance" },
  { code: "2A5X4", title: "Refuel/Bomber Aircraft Maintenance", category: "Maintenance" },
  { code: "2A6X1", title: "Aerospace Propulsion", category: "Maintenance" },
  { code: "2A6X2", title: "Aerospace Ground Equipment", category: "Maintenance" },
  { code: "2A6X3", title: "Aircrew Egress Systems", category: "Maintenance" },
  { code: "2A6X4", title: "Aircraft Fuel Systems", category: "Maintenance" },
  { code: "2A6X5", title: "Aircraft Hydraulic Systems", category: "Maintenance" },
  { code: "2A6X6", title: "Aircraft Electrical and Environmental Systems", category: "Maintenance" },
  { code: "2A7X1", title: "Aircraft Metals Technology", category: "Maintenance" },
  { code: "2A7X2", title: "Nondestructive Inspection", category: "Maintenance" },
  { code: "2A7X3", title: "Aircraft Structural Maintenance", category: "Maintenance" },
  { code: "2A7X5", title: "Low Observable Aircraft Structural Maintenance", category: "Maintenance" },
  { code: "2A8X1", title: "Mobility Air Forces Integrated Avionics", category: "Maintenance" },
  { code: "2A8X2", title: "Mobility Air Forces Integrated Communication/Nav/Mission Systems", category: "Maintenance" },
  { code: "2A9X1", title: "Bomber/Special Aircraft Integrated Avionics", category: "Maintenance" },
  { code: "2A9X2", title: "Bomber/Special Aircraft Communication/Nav/Mission Systems", category: "Maintenance" },
  { code: "2A9X3", title: "Bomber/Special Aircraft Electronic Warfare/Radar Systems", category: "Maintenance" },
  // ---- 2F-2W Munitions / Logistics / Vehicles -------------------------
  { code: "2F0X1", title: "Fuels", category: "Logistics" },
  { code: "2G0X1", title: "Logistics Plans", category: "Logistics" },
  { code: "2M0X1", title: "Missile and Space Systems Electronic Maintenance", category: "Maintenance" },
  { code: "2M0X2", title: "Missile and Space Systems Maintenance", category: "Maintenance" },
  { code: "2M0X3", title: "Missile and Space Facilities", category: "Maintenance" },
  { code: "2P0X1", title: "Precision Measurement Equipment Laboratory", category: "Maintenance" },
  { code: "2R0X1", title: "Maintenance Management Analysis", category: "Maintenance" },
  { code: "2R1X1", title: "Maintenance Management Production", category: "Maintenance" },
  { code: "2S0X1", title: "Materiel Management", category: "Logistics" },
  { code: "2T0X1", title: "Traffic Management", category: "Logistics" },
  { code: "2T1X1", title: "Ground Transportation", category: "Logistics" },
  { code: "2T2X1", title: "Air Transportation", category: "Logistics" },
  { code: "2T3X1", title: "Mission Generation Vehicular Equipment Maintenance", category: "Logistics" },
  { code: "2W0X1", title: "Munitions Systems", category: "Maintenance" },
  { code: "2W1X1", title: "Aircraft Armament Systems", category: "Maintenance" },
  { code: "2W2X1", title: "Nuclear Weapons", category: "Maintenance" },
  // ---- 3D / 3E / 3F / 3M Cyber Systems / Civil Engineer / Support ----
  { code: "3D0X2", title: "Cyber Systems Operations", category: "Cyber" },
  { code: "3D0X3", title: "Cyber Surety", category: "Cyber" },
  { code: "3D0X4", title: "Computer Systems Programming", category: "Cyber" },
  { code: "3D1X1", title: "Client Systems", category: "Cyber" },
  { code: "3D1X2", title: "Cyber Transport Systems", category: "Cyber" },
  { code: "3D1X3", title: "RF Transmission Systems", category: "Cyber" },
  { code: "3D1X4", title: "Spectrum Operations", category: "Cyber" },
  { code: "3D1X5", title: "Radar, Airfield, and Weather Systems", category: "Cyber" },
  { code: "3E0X1", title: "Electrical Systems", category: "Civil Engineer" },
  { code: "3E1X1", title: "Heating, Ventilation, AC, and Refrigeration", category: "Civil Engineer" },
  { code: "3E2X1", title: "Pavements and Construction Equipment", category: "Civil Engineer" },
  { code: "3E3X1", title: "Structural", category: "Civil Engineer" },
  { code: "3E4X1", title: "Water and Fuel Systems Maintenance", category: "Civil Engineer" },
  { code: "3E5X1", title: "Engineering", category: "Civil Engineer" },
  { code: "3E6X1", title: "Operations Management", category: "Civil Engineer" },
  { code: "3E7X1", title: "Fire Protection", category: "Civil Engineer" },
  { code: "3E8X1", title: "Explosive Ordnance Disposal", category: "Civil Engineer" },
  { code: "3E9X1", title: "Emergency Management", category: "Civil Engineer" },
  { code: "3F0X1", title: "Personnel", category: "Support" },
  { code: "3F1X1", title: "Services", category: "Support" },
  { code: "3F2X1", title: "Education and Training", category: "Support" },
  { code: "3F3X1", title: "Manpower", category: "Support" },
  { code: "3F4X1", title: "Equal Opportunity", category: "Support" },
  { code: "3F5X1", title: "Personnel", category: "Support" },
  { code: "3M0X1", title: "Services", category: "Support" },
  { code: "3N0X2", title: "Broadcaster", category: "Public Affairs" },
  { code: "3N0X5", title: "Photojournalist", category: "Public Affairs" },
  { code: "3N1X1", title: "Regional Band", category: "Music" },
  { code: "3N2X1", title: "Premier Band", category: "Music" },
  { code: "3P0X1", title: "Security Forces", category: "Security Forces" },
  // ---- 4 Medical ------------------------------------------------------
  { code: "4A0X1", title: "Health Services Management", category: "Medical" },
  { code: "4A1X1", title: "Medical Materiel", category: "Medical" },
  { code: "4A2X1", title: "Biomedical Equipment", category: "Medical" },
  { code: "4B0X1", title: "Bioenvironmental Engineering", category: "Medical" },
  { code: "4C0X1", title: "Mental Health Service", category: "Medical" },
  { code: "4D0X1", title: "Diet Therapy", category: "Medical" },
  { code: "4E0X1", title: "Public Health", category: "Medical" },
  { code: "4H0X1", title: "Cardiopulmonary Laboratory", category: "Medical" },
  { code: "4J0X2", title: "Physical Medicine", category: "Medical" },
  { code: "4M0X1", title: "Aerospace and Operational Physiology", category: "Medical" },
  { code: "4N0X1", title: "Aerospace Medical Service", category: "Medical" },
  { code: "4N1X1", title: "Surgical Service", category: "Medical" },
  { code: "4P0X1", title: "Pharmacy", category: "Medical" },
  { code: "4R0X1", title: "Diagnostic Imaging", category: "Medical" },
  { code: "4T0X1", title: "Medical Laboratory", category: "Medical" },
  { code: "4V0X1", title: "Optometry", category: "Medical" },
  { code: "4Y0X1", title: "Dental Assistant", category: "Medical" },
  { code: "4Y0X2", title: "Dental Laboratory", category: "Medical" },
  // ---- 5 Chaplain / Legal / Finance ----------------------------------
  { code: "5J0X1", title: "Paralegal", category: "Legal" },
  { code: "5R0X1", title: "Chaplain Assistant (Religious Affairs)", category: "Chaplain" },
  // ---- 6 Comptroller / Acquisitions ----------------------------------
  { code: "6C0X1", title: "Contracting", category: "Acquisitions" },
  { code: "6F0X1", title: "Financial Management and Comptroller", category: "Comptroller" },
  // ---- 7 Special Investigations / Recruiting -------------------------
  { code: "7S0X1", title: "Special Investigations (OSI)", category: "Investigations" },
  { code: "8R000", title: "Recruiter", category: "Recruiter" },
  { code: "8C000", title: "First Sergeant", category: "Senior Enlisted" },
  { code: "9E000", title: "Command Chief Master Sergeant", category: "Senior Enlisted" },
];

const SPACE_FORCE_AFSC: MosEntry[] = [
  // ---- Officer ---------------------------------------------------------
  { code: "13SX", title: "Space Operations Officer", category: "Operations" },
  { code: "14NX", title: "Intelligence Officer", category: "Intelligence" },
  { code: "17DX", title: "Cyberspace Operations Officer", category: "Cyber" },
  { code: "17SX", title: "Cyber Warfare Operations Officer", category: "Cyber" },
  { code: "32EX", title: "Acquisitions Engineering Officer", category: "Acquisitions" },
  { code: "62EX", title: "Developmental Engineer", category: "Engineering" },
  { code: "63AX", title: "Acquisition Manager", category: "Acquisitions" },
  // ---- Enlisted (5C / 5D / 5I / 5J / 5R series) ----------------------
  { code: "1C6X1", title: "Space Systems Operations", category: "Operations" },
  { code: "1D7X1Q", title: "Network Operations (Space)", category: "Cyber" },
  { code: "1N0X1", title: "All Source Intelligence Analyst", category: "Intelligence" },
  { code: "1N1X1", title: "Geospatial Intelligence", category: "Intelligence" },
  { code: "1N2X1", title: "Signals Intelligence Analyst", category: "Intelligence" },
  { code: "1N4X1", title: "Network Intelligence Analyst", category: "Intelligence" },
  { code: "1N8X1", title: "Targeting Analyst", category: "Intelligence" },
  { code: "5C0X1", title: "Space Systems Operations (Specialty Code)", category: "Operations" },
  { code: "5C0X2", title: "Cyber Operations (Space)", category: "Cyber" },
  { code: "5D0X1", title: "Cyber Systems Operations (Space)", category: "Cyber" },
  { code: "5D0X2", title: "Cyber Defense Operations (Space)", category: "Cyber" },
  { code: "5I0X1", title: "Intelligence (Space)", category: "Intelligence" },
  { code: "5J0X1", title: "Cyber Warfare Operations (Space)", category: "Cyber" },
  { code: "5R0X1", title: "Cyber Defense Operations (Space)", category: "Cyber" },
  { code: "5S0X1", title: "Space Systems Operations (Senior Specialty)", category: "Operations" },
  { code: "5T0X1", title: "Space Operations Test", category: "Operations" },
];

const COAST_GUARD_RATINGS: MosEntry[] = [
  // ---- Aviation -------------------------------------------------------
  { code: "AET", title: "Avionics Electrical Technician", category: "Aviation" },
  { code: "AMT", title: "Aviation Maintenance Technician", category: "Aviation" },
  { code: "AST", title: "Aviation Survival Technician (Rescue Swimmer)", category: "Aviation" },
  // ---- Deck and ordnance ---------------------------------------------
  { code: "BM", title: "Boatswain's Mate", category: "Deck" },
  { code: "GM", title: "Gunner's Mate", category: "Weapons" },
  { code: "MK", title: "Machinery Technician", category: "Engineering" },
  { code: "DC", title: "Damage Controlman", category: "Engineering" },
  { code: "EM", title: "Electrician's Mate", category: "Engineering" },
  // ---- Information / Operations --------------------------------------
  { code: "ET", title: "Electronics Technician", category: "Information Systems" },
  { code: "IT", title: "Information Systems Technician", category: "Information Systems" },
  { code: "OS", title: "Operations Specialist", category: "Operations" },
  { code: "ME", title: "Maritime Enforcement Specialist", category: "Maritime Enforcement" },
  { code: "IS", title: "Intelligence Specialist", category: "Intelligence" },
  { code: "MST", title: "Marine Science Technician", category: "Operations" },
  { code: "ITC", title: "Information Systems Technician (Cyber)", category: "Information Systems" },
  // ---- Special Operations / Diving -----------------------------------
  { code: "DV", title: "Diver", category: "Special Operations" },
  { code: "MSRT", title: "Maritime Security Response Team Operator", category: "Special Operations" },
  // ---- Support --------------------------------------------------------
  { code: "CS", title: "Culinary Specialist", category: "Support" },
  { code: "HS", title: "Health Services Technician", category: "Medical" },
  { code: "PA", title: "Public Affairs Specialist", category: "Support" },
  { code: "SK", title: "Storekeeper", category: "Logistics" },
  { code: "YN", title: "Yeoman", category: "Administration" },
  { code: "MUS", title: "Musician", category: "Administration" },
  // ---- Officer Specialty Codes (selected) ----------------------------
  { code: "AVI", title: "Aviator", category: "Officer Specialty" },
  { code: "DECK", title: "Deck Watch / Cutterman", category: "Officer Specialty" },
  { code: "ENG", title: "Engineering Officer in Charge", category: "Officer Specialty" },
  { code: "INT", title: "Intelligence Officer", category: "Officer Specialty" },
];

const MOS_BY_BRANCH: Record<Branch["code"], MosEntry[]> = {
  army: ARMY_MOS,
  navy: NAVY_RATINGS,
  marines: USMC_MOS,
  air_force: AIR_FORCE_AFSC,
  space_force: SPACE_FORCE_AFSC,
  coast_guard: COAST_GUARD_RATINGS,
};

export function listMosForBranch(code: Branch["code"] | null): MosEntry[] {
  if (!code) return [];
  return MOS_BY_BRANCH[code] ?? [];
}

export function findMosEntry(
  code: Branch["code"] | null,
  mosCode: string | null | undefined,
): MosEntry | null {
  if (!code || !mosCode) return null;
  const norm = mosCode.trim().toUpperCase();
  return (
    MOS_BY_BRANCH[code]?.find((m) => m.code.toUpperCase() === norm) ?? null
  );
}
